name: "gtd-manager"
description: "Extract and register only the incomplete tasks from yesterday's issue into a new issue"
inputs:
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: true
  TIME_ZONE:
    description: "Time zone"
    default: "UTC"
  LABEL:
    description: "Label name"
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y curl gzip

    - name: Determine Architecture
      shell: bash
      run: echo "arch=$(uname -m)" >> $GITHUB_ENV

    - name: Set Binary URL
      shell: bash
      run: |
        if [ "$arch" = "aarch64" ]; then
          echo "BINARY_URL=https://github.com/hxrxchang/gtd-manager/releases/download/v0.1.2/gtd-manager_Linux_arm64.tar.gz" >> $GITHUB_ENV
        elif [ "$arch" = "x86_64" ]; then
          echo "BINARY_URL=https://github.com/hxrxchang/gtd-manager/releases/download/v0.1.2/gtd-manager_Linux_x86_64.tar.gz" >> $GITHUB_ENV
        fi

    - name: Install gtd-manager
      shell: bash
      run: |
        curl -L $BINARY_URL --output gtd-manager.gz
        tar -xzf gtd-manager.gz

    - name: Run
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        TZ: ${{ inputs.TIME_ZONE }}
        LABEL: ${{ inputs.LABEL }}
      run: |
        if [ -n "$LABEL" ]; then
          options="-label $LABEL"
        else
          options=""
        fi

        echo $options

        ./gtd-manager $options
