name: "Create a new issue"
description: "Extract and register only the incomplete tasks from yesterday's issue into a new issue"
inputs:
  ACCESS_TOKEN: # id of input
    description: "Access token which has read and write access to issues"
    required: true
    default: ""
  REPOSITORY:
    description: "Repository name"
    required: true
    default: ""
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - name: Run
      shell: bash
      run: ACCESS_TOKEN=${{ inputs.ACCESS_TOKEN}} REPOSITORY=${{ inputs.REPOSITORY }} go run cmd/gtd/main.go
