name: "gtd-manager"
description: "Extract and register only the incomplete tasks from yesterday's issue into a new issue"
inputs:
  GITHUB_TOKEN: # id of input
    description: "Access token which has read and write access to issues"
    required: true
    default: ""
  GITHUB_REPOSITORY:
    description: "Repository name"
    required: true
    default: ""
  TIME_ZONE:
    description: "Time zone"
    default: "UTC"
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - name: Install gtd
      shell: bash
      run: |
        go install github.com/hxrxchang/gtd-manager/cmd/gtd@latest

    - name: Run
      shell: bash
      env:
        TZ: ${{ inputs.TIME_ZONE }}
      run: |
        options=""
        if [ -n "$LABEL" ]; then
          options="$options -label \"$LABEL\""
        fi

        command $options
        GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN}} GITHUB_REPOSITORY=${{ inputs.GITHUB_REPOSITORY }} gtd $options
