name: "Create a new issue"
description: "Extract and register only the incomplete tasks from yesterday's issue into a new issue"
inputs:
  ACCESS_TOKEN: # id of input
    description: "Access token which has read and write access to issues"
    required: true
    default: ""
  REPOSITORY:
    description: "Repository name"
    required: true
    default: ""
  TIME_ZONE:
    description: "Time zone"
    default: "UTC"
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - name: Install gtd
      shell: bash
      run: |
        go install github.com/hxrxchang/gtd-manager/cmd/gtd@latest

    - name: Run
      shell: bash
      env:
        TZ: ${{ inputs.TIME_ZONE }}
      run: ACCESS_TOKEN=${{ inputs.ACCESS_TOKEN}} REPOSITORY=${{ inputs.REPOSITORY }} gtd
